/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;

public class App {

    public static void main(String[] args) {
        /*String meunome = "Pedro";
    int minhaidade;
    minhaidade = 15;
    double minhaaltura = 1.71;
    boolean jaquinzei = true;
    char minhaInicial = 'P' ;
     System.out.println("Meu nome: "+meunome);
     System.out.println("Minha idade: "+minhaidade);
         */
 /*int num = 5;
    if (num>14){
        System.out.println("BOMBOU");
    }
    else if (num<0){
        System.out.println("SEILA FODASE");
    }
    else{
        System.out.println("NAO BOMBOU");
    }
         */
        /*int num = 1;
        switch (num) {
            case 1:
                System.out.println("Domingo");
                break;
            case 2:
                System.out.println("Segunda");
                break;
            case 3:
                System.out.println("Terca");
                break;
            case 4:
                System.out.println("Quarta");
                break;
            case 5:
                System.out.println("Quinta");
                break;
            case 6:
                System.out.println("Sexta");
                break;
            case 7:
                System.out.println("Sabado");
                break;
            default:
                System.out.println("Errou");
        }
        */
        /*int numero = 2;
        String resultado = (numero%2==0) ? "Par" : "Impar";
        System.out.println("Meu resultado: "+resultado);*/
        //1
        int numero = 2;
        String posneg = (numero>0) ? "Postivo" : "Negativo";
        System.out.println("P/N: "+posneg);
        //2
        String idade = (numero>=18) ? "Maior" : "Menor";
        System.out.println("Maior ou Menor: "+idade);
        //3
        int num1 = 2;
        int num2 = 3;
        String maior = (num1>num2) ? "NUMERO 1 MAIOR" : "NUMERO 2 MAIOR";
        System.out.println("Maior: "+maior);
        //4
        String resultado = (numero%2==0) ? "Par" : "Impar";
        System.out.println("Meu resultado: "+resultado);
    }
}
