/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetojava;

public class App {
    public static void main(String[] args){
    String nome = "Pedro"; // caracteres
    int idade = 15; // numeros inteiros
    double altura = 1.71; // numeros com decimais
    boolean setJava = true; // booleans
    char letrainicial = 'P'; // apenas 1 caracter
    int num1 = 7;
    int num2 = 5;
    int num3 = 8;
    int resto = num1 %2;
    System.out.println("Nome: "+ nome+", Idade: "+idade+", LetraInicial: "+letrainicial);
    System.out.println("Soma: "+ (num1 + num2));
    System.out.println("Media: "+(num1+num2+num3)/3);
    if(resto==0){
        System.out.println("Resto ParImpar:  Par");
    }
    else if(resto==1){
                System.out.println("Resto ParImpar:  Impar");
    }
    }
}
