/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Conexao;

import java.sql.Connection;

public class App {
    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        if(conexao != null){
        CriarTabela.criarTabelaUsuarios(conexao);
        InserirUsuario.inserirUsuario(conexao,"pinter","pinter69@gmail.com");
        ListarUsuarios.listarUsuarios(conexao);
        conexaoSQLite.desconectar(conexao);
        }
    }
}
