/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arrays;

public class App {

    public static void main(String[] args) {
        /*
        int[] numeros;
        numeros = new int[5];
        int[] numeros2 = {1,2,3,4,5,6,7,8,9,10};
        
        System.out.println(numeros2[0]);
        
        numeros2[0] = 90;
        
        System.out.println(numeros2[0]);
        System.out.println(numeros2.length);
        for(int i = 0; i < numeros2.length; i++){
         System.out.println(numeros2[i]);
        }
        for (int numero : numeros2){
        System.out.println(numero);}
    */
        String[] nomes = {"naruto","shikamaru","gaara","sasuke","obito"};
        nomes[2] = "Jobiscléison";
        for (String nomesseila : nomes){
        System.out.println(nomesseila);}
    }
}
